import {AssetInfoFull, AssetInfoPartial, AssetTree, MetaAssetsDiff} from '../types';
import {diffAssets, serailizeAssetInfo, toFullAssetInfo} from './asset-info';
import {
  assetInfoTreeToList,
  getAssetInfoById,
  getRelativePathToAssetInfo,
  getSha1ToAssetInfo,
} from './dir-assets';

/**
 * Get what should be changed to align refer asset info list with latest asset info list.
 * ONLY limited to the same rootDir, so use relativePath as id
 * @param referAssetInfoList, get from dir meta file
 * @param latestAssetInfoList, get from lastest content, use AssetInfoPartial here to reduce cost, get full asset info only necessary.
 * @returns
 */
export async function diffAssetInfoList(
  referAssetInfoList: AssetInfoFull[],
  latestAssetInfoList: AssetInfoPartial[],
  config: {
    rootDir: string;
  }
): Promise<MetaAssetsDiff> {
  const {rootDir} = config;
  const pathToInfo1 = getRelativePathToAssetInfo(referAssetInfoList);
  const sha1ToAssetInfo1 = getSha1ToAssetInfo(referAssetInfoList);
  const pathToInfo2 = getRelativePathToAssetInfo(latestAssetInfoList as AssetInfoFull[]);

  const paths1 = Object.keys(pathToInfo1);
  const paths2 = Object.keys(pathToInfo2);
  const pathAll = Array.from(new Set([...paths1, ...paths2]));
  const pathOnlyIn2: string[] = [];
  const pathOnlyIn1: string[] = [];
  const pathCommon: string[] = [];
  for (const p of pathAll) {
    let cnt = 0;
    cnt |= pathToInfo1[p] ? 1 : 0;
    cnt |= pathToInfo2[p] ? 2 : 0;
    if (cnt === 1) {
      pathOnlyIn1.push(p);
    } else if (cnt === 2) {
      pathOnlyIn2.push(p);
    } else if (cnt === 3) {
      pathCommon.push(p);
    } else {
      throw new Error(`id should not equal to ${p}`);
    }
  }

  /** new assets */
  const added: AssetInfoFull[] = [];
  /** new assets generated by copy exist asset */
  const copied: {
    from: AssetInfoFull;
    to: AssetInfoFull;
  }[] = [];
  /** new assets generated by move exist asset */
  const moved: {
    from: AssetInfoFull;
    to: AssetInfoFull;
  }[] = [];
  /** assets that are modified */
  const modified: {
    from: AssetInfoFull;
    to: AssetInfoFull;
    changed: Partial<AssetInfoFull>;
  }[] = [];
  /** assets that are deleted */
  let deleted: AssetInfoFull[] = [];

  /**
   * All cases:
   * 1. new file
   * 2. copied from file in 1: shortId exist in file of 1
   * 3. move from file in 1:
   */
  /** go through relative path only in current assets meta */
  for (const p of pathOnlyIn2) {
    const info = pathToInfo2[p];
    const fullInfo = await toFullAssetInfo(info, rootDir);
    const {sha1} = fullInfo;
    const info1 = getAssetInfoById(sha1ToAssetInfo1, sha1);

    /** if can't find asset info by sha1 on referred assets meta, it's a new asset */
    if (!info1) {
      added.push(fullInfo);
      continue;
    }
    const {relativePath} = info1;
    if (pathCommon.includes(relativePath)) {
      /** if the asset is in both referred and current assets meta, it's a copied asset */
      copied.push({
        from: info1,
        to: fullInfo,
      });
    } else if (pathOnlyIn1.includes(relativePath)) {
      /** if the asset is in referred assets meta but not in current assets meta, it's a moved asset */
      moved.push({
        from: info1,
        to: fullInfo,
      });
    }
  }
  for (const p of pathCommon) {
    const info1 = pathToInfo1[p];
    const info2 = pathToInfo2[p];
    const changed = diffAssets(info2, info1);
    if (changed) {
      /** Once there are asset props change, should recalculate assets sha1 */
      const newInfo2 = await toFullAssetInfo(info2, rootDir);
      const changed2 = diffAssets(newInfo2, info1);
      if (changed2) {
        modified.push({
          from: info1,
          to: newInfo2,
          changed,
        });
      }
    }
  }

  const pathOfMovedIn1 = moved.map(it => it.from.relativePath);
  deleted = pathOnlyIn1.filter(p => !pathOfMovedIn1.includes(p)).map(p => pathToInfo1[p]);

  const isNeedAction =
    [added, copied, moved, modified, deleted].reduce<number>((sum, it) => {
      return sum + it.length;
    }, 0) > 0;
  return {
    added,
    copied,
    moved,
    modified,
    deleted,
    isNeedAction,
  };
}

// export function diffAssetMeta(referMeta: AssetTree | AssetInfoFull[], latestMeta: AssetTree | AssetInfoFull[]) {
//   const referMetaList = Array.isArray(referMeta) ? referMeta : assetInfoTreeToList(referMeta);
//   const latestMetaList = Array.isArray(latestMeta) ? latestMeta : assetInfoTreeToList(latestMeta);
//   return diffAssetInfoList(referMetaList, latestMetaList, {rootDir: referMeta.rootDir as string});
// }

export function serializeMetaAssetsDiff(stateChange: MetaAssetsDiff) {
  return {
    ...stateChange,
    added: stateChange.added.map(it => serailizeAssetInfo(it)),
    deleted: stateChange.deleted.map(it => serailizeAssetInfo(it)),
    copied: stateChange.copied.map(it => {
      return {
        ...it,
        from: serailizeAssetInfo(it.from),
        to: serailizeAssetInfo(it.to),
      };
    }),
    moved: stateChange.moved.map(it => {
      return {
        ...it,
        from: serailizeAssetInfo(it.from),
        to: serailizeAssetInfo(it.to),
      };
    }),
    modified: stateChange.modified.map(it => {
      return {
        ...it,
        from: serailizeAssetInfo(it.from),
        to: serailizeAssetInfo(it.to),
        changed: serailizeAssetInfo(it.changed),
      };
    }),
  };
}

export function getActionsFromAssetsChange(stateChange: MetaAssetsDiff) {
  const {added = [], copied = [], moved = [], modified = [], deleted = [], isNeedAction} = stateChange;
  const toAdd: AssetInfoFull[] = [...added, ...copied.map(it => it.to), ...moved.map(it => it.to)];
  const toDelete: AssetInfoFull[] = [...deleted, ...moved.map(it => it.from)];
  const toModify = modified;
  return {toAdd, toDelete, toModify, isNeedAction};
}
