import {AssetInfoFull, AssetMeta, MetaDiff} from '../types';
import {diffAssets, serailizeAssetInfo, toFullAssetInfo} from './asset-info';
import {
  getAssetInfoById,
  getAssetInfoListFromMeta,
  getRelativePathToAssetInfo,
  getSha1ToAssetInfo,
} from './assets-meta';

type DiffResult = Pick<MetaDiff, 'added' | 'copied' | 'moved' | 'modified' | 'deleted'>;
/**
 * use relativePath as id for assets syncup
 * @param toMeta
 * @param fromMeta
 * @returns
 */
export async function diffMetaForSyncUp(
  toMeta: AssetMeta,
  fromMeta: AssetMeta,
  options: {isSameDir?: boolean}
): Promise<DiffResult> {
  const {isSameDir} = options ?? {};
  const {rootDir: rootDir2} = fromMeta;
  const assetInfoList1 = getAssetInfoListFromMeta(toMeta);
  const assetInfoList2 = getAssetInfoListFromMeta(fromMeta);
  const pathToInfo1 = getRelativePathToAssetInfo(assetInfoList1);
  const sha1ToAssetInfo1 = getSha1ToAssetInfo(assetInfoList1);
  const pathToInfo2 = getRelativePathToAssetInfo(assetInfoList2);

  const paths1 = Object.keys(pathToInfo1);
  const paths2 = Object.keys(pathToInfo2);
  const pathAll = Array.from(new Set([...paths1, ...paths2]));
  const pathOnlyIn2: string[] = [];
  const pathOnlyIn1: string[] = [];
  const pathCommon: string[] = [];
  for (const p of pathAll) {
    let cnt = 0;
    cnt |= pathToInfo1[p] ? 1 : 0;
    cnt |= pathToInfo2[p] ? 2 : 0;
    if (cnt === 1) {
      pathOnlyIn1.push(p);
    } else if (cnt === 2) {
      pathOnlyIn2.push(p);
    } else if (cnt === 3) {
      pathCommon.push(p);
    } else {
      throw new Error(`id should not equal to ${p}`);
    }
  }

  /** new assets */
  const added: AssetInfoFull[] = [];
  /** new assets generated by copy exist asset */
  const copied: {
    from: AssetInfoFull;
    to: AssetInfoFull;
  }[] = [];
  /**
   * new assets generated by move exist asset
   * move is a kind of copy and delete, but use move can reduce cost of disk
   * Only work for the case isSameDir
   */
  const moved: {
    from: AssetInfoFull;
    to: AssetInfoFull;
  }[] = [];
  /** assets that are modified */
  const modified: {
    from: AssetInfoFull;
    to: AssetInfoFull;
    changed?: Partial<AssetInfoFull>;
  }[] = [];
  const pathOfMovedIn1: string[] = [];
  /** assets that are deleted */
  let deleted: AssetInfoFull[] = [];

  /**
   * All cases:
   * 1. new file
   * 2. copied from file in 1: shortId exist in file of 1
   * 3. move from file in 1:
   */
  /** go through relative path only in from assets meta */
  for (const p of pathOnlyIn2) {
    const info = pathToInfo2[p];
    const fullInfo = await toFullAssetInfo(info, rootDir2);
    const {sha1} = fullInfo;
    const info1 = sha1ToAssetInfo1[sha1];
    // const info1 = getAssetInfoById(sha1ToAssetInfo1, sha1);

    /** if can't find asset info by sha1 on assets meta1 by sha1, it's a new asset */
    if (!info1) {
      added.push(fullInfo);
      continue;
    }
    /** Try find move action to reduce disk cost */
    let moveFromFile: AssetInfoFull;
    if (Array.isArray(info1)) {
      moveFromFile = info1.find(it => {
        const {relativePath} = it;
        return pathOnlyIn1.includes(relativePath) && !pathOfMovedIn1.includes(relativePath);
      });
    } else {
      const {relativePath} = info1;
      if (pathOnlyIn1.includes(relativePath) && !pathOfMovedIn1.includes(relativePath)) {
        moveFromFile = info1;
      }
    }
    if (moveFromFile) {
      pathOfMovedIn1.push(moveFromFile.relativePath);
      moved.push({
        from: moveFromFile,
        to: fullInfo,
      });
    } else {
      copied.push({
        from: Array.isArray(info1) ? info1[0] : info1,
        to: fullInfo,
      });
    }
  }
  for (const p of pathCommon) {
    const info1 = pathToInfo1[p];
    const info2 = pathToInfo2[p];
    const changed = diffAssets(info2, info1, isSameDir ? ['changeDate', 'modifyDate', 'size'] : ['sha1']);
    if (changed) {
      if (isSameDir) {
        /** Once there are asset props change, should recalculate assets sha1 */
        const newInfo2 = await toFullAssetInfo(info2, rootDir2);
        const changed2 = diffAssets(newInfo2, info1);
        if (changed2) {
          modified.push({
            from: info1,
            to: newInfo2,
            changed: changed,
          });
        }
      } else {
        modified.push({
          from: info1,
          to: info2,
        });
      }
    }
  }

  deleted = pathOnlyIn1.filter(p => !pathOfMovedIn1.includes(p)).map(p => pathToInfo1[p]);

  return {
    added,
    copied,
    moved,
    modified,
    deleted,
  };
}

export async function diffMetaForImportNew(toMeta: AssetMeta, fromMeta: AssetMeta): Promise<DiffResult> {
  // const {rootDir: rootDir1} = toMeta;
  const {rootDir: rootDir2} = fromMeta;
  const assetInfoList1 = getAssetInfoListFromMeta(toMeta);
  const assetInfoList2 = getAssetInfoListFromMeta(fromMeta);
  const sha1ToAssetInfo1 = getSha1ToAssetInfo(assetInfoList1);
  const sha1ToAssetInfo2 = getSha1ToAssetInfo(assetInfoList2);

  const added: AssetInfoFull[] = [];
  for (const key of Object.keys(sha1ToAssetInfo2)) {
    const assetInfo1 = sha1ToAssetInfo1[key];
    if (assetInfo1) {
      continue;
    }
    added.push(await toFullAssetInfo(getAssetInfoById(sha1ToAssetInfo2, key), rootDir2));
  }
  return {added};
}

/**
 * Get what should be changed to align refer asset info list with latest asset info list.
 * ONLY limited to the same rootDir, so use relativePath as id
 * @param referAssetInfoList, get from dir meta file
 * @param latestAssetInfoList, get from lastest content, use AssetInfoPartial here to reduce cost, get full asset info only necessary.
 * @returns
 */
export async function diffMeta(
  toMeta: AssetMeta,
  fromMeta: AssetMeta,
  options?: {
    forOperation: 'syncUp' | 'importNew';
  }
): Promise<MetaDiff> {
  const {rootDir: rootDir1} = toMeta;
  const {rootDir: rootDir2} = fromMeta;
  const isSameDir = rootDir1 === rootDir2;
  const forOperation = options?.forOperation ?? (isSameDir ? 'syncUp' : 'importNew');
  let diff: DiffResult;
  if (forOperation === 'syncUp') {
    diff = await diffMetaForSyncUp(toMeta, fromMeta, {isSameDir});
  } else if (forOperation === 'importNew') {
    diff = await diffMetaForImportNew(toMeta, fromMeta);
  } else {
    throw new Error(`Invalid usedFor: ${forOperation}`);
  }
  const {added = [], copied = [], moved = [], modified = [], deleted = []} = diff;
  const isNeedAction =
    [added, copied, moved, modified, deleted].reduce<number>((sum, it) => {
      return sum + it.length;
    }, 0) > 0;

  return {
    forOperation,
    toDir: rootDir1,
    fromDir: rootDir2,
    isNeedAction,
    ...diff,
  };
}

// export function diffAssetMeta(from: MetaInfo, to: MetaInfo) {}
export function serializeMetaDiff(stateChange: MetaDiff) {
  return {
    ...stateChange,
    added: stateChange.added?.map(it => serailizeAssetInfo(it)),
    deleted: stateChange.deleted?.map(it => serailizeAssetInfo(it)),
    copied: stateChange.copied?.map(it => {
      return {
        ...it,
        from: serailizeAssetInfo(it.from),
        to: serailizeAssetInfo(it.to),
      };
    }),
    moved: stateChange.moved?.map(it => {
      return {
        ...it,
        from: serailizeAssetInfo(it.from),
        to: serailizeAssetInfo(it.to),
      };
    }),
    modified: stateChange.modified?.map(it => {
      return {
        ...it,
        from: serailizeAssetInfo(it.from),
        to: serailizeAssetInfo(it.to),
        changed: serailizeAssetInfo(it.changed),
      };
    }),
  };
}
