import assert from 'assert';
import {AssetInfoFull, AssetMeta, MetaDiffForImportNew, MetaDiffForSyncUp} from '../types';
import {diffAssets, serailizeAssetInfo, toFullAssetInfo} from './asset-info';
import {getAssetInfoListFromMeta, getRelativePathToAssetInfo, getSha1ToAssetInfo} from './assets-meta';

/**
 * diff meta for asset syncup, the meta may comes from same dir or different dir.
 * - for same dir, it's used to do syncup between latest assets and its meta
 * - for different dir, it's used to do syncup assets and its meta,
 *   the meta of source and target must aligned with its latest assets.
 * @returns diff result for syncup
 */
export async function diffMetaForSyncUp(
  targetMeta: AssetMeta,
  sourceMeta: AssetMeta
): Promise<MetaDiffForSyncUp> {
  const {rootDir: targetRootDir} = targetMeta;
  const {rootDir: sourceRootDir} = sourceMeta;

  const targetAssetList = getAssetInfoListFromMeta(targetMeta);
  const sourceAssetList = getAssetInfoListFromMeta(sourceMeta);

  const isSameDir = targetRootDir === sourceRootDir;
  /** check asset info */
  assert(
    targetAssetList.every(it => it.sha1 !== undefined),
    'every item in targetAssetList must be full asset info.'
  );
  if (!isSameDir) {
    assert(
      sourceAssetList.every(it => it.sha1 !== undefined),
      'every item in sourceAssetList must be full asset info.'
    );
  }

  const pathToAssetInTarget = getRelativePathToAssetInfo(targetAssetList);
  const sha1ToAssetInTarget = getSha1ToAssetInfo(targetAssetList);
  const pathToAssetInSource = getRelativePathToAssetInfo(sourceAssetList);

  const pathListInTarget = Object.keys(pathToAssetInTarget);
  const pathListInSource = Object.keys(pathToAssetInSource);
  const pathAll = Array.from(new Set([...pathListInTarget, ...pathListInSource]));
  const pathOnlyInSource: string[] = [];
  const pathOnlyInTarget: string[] = [];
  const pathCommon: string[] = [];
  for (const p of pathAll) {
    let cnt = 0;
    cnt |= pathToAssetInTarget[p] ? 1 : 0;
    cnt |= pathToAssetInSource[p] ? 2 : 0;
    if (cnt === 1) {
      pathOnlyInTarget.push(p);
    } else if (cnt === 2) {
      pathOnlyInSource.push(p);
    } else if (cnt === 3) {
      pathCommon.push(p);
    } else {
      throw new Error(`id should not equal to ${p}`);
    }
  }

  /** new assets */
  const added: AssetInfoFull[] = [];
  /** new assets generated by copy exist asset */
  const copied: {
    from: AssetInfoFull;
    to: AssetInfoFull;
  }[] = [];
  /**
   * new assets generated by move exist asset
   * move is a kind of copy and delete, but use move can reduce cost of disk
   * Only work for the case isSameDir
   */
  const moved: {
    from: AssetInfoFull;
    to: AssetInfoFull;
  }[] = [];
  /** assets that are modified */
  const modified: {
    from: AssetInfoFull;
    to: AssetInfoFull;
    changed?: Partial<AssetInfoFull>;
  }[] = [];
  /**
   * save moved path in target, as move can only happen once.
   */
  const pathOfMovedInTarget: string[] = [];
  /** assets that are deleted */
  let deleted: AssetInfoFull[] = [];

  /**
   * All cases:
   * 1. new file
   * 2. copied from file in 1: shortId exist in file of 1
   * 3. move from file in 1:
   */
  /** go through relative path only in from assets meta */
  for (const p of pathOnlyInSource) {
    const sourceAsset = await toFullAssetInfo(pathToAssetInSource[p], sourceRootDir);
    const {sha1} = sourceAsset;
    const assetInTarget = sha1ToAssetInTarget[sha1];
    // const info1 = getAssetInfoById(sha1ToAssetInfo1, sha1);

    /** if can't find asset info by sha1 on assets meta1 by sha1, it's a new asset */
    if (!assetInTarget) {
      added.push(sourceAsset);
      continue;
    }
    /** Try find move action to reduce disk cost */
    let movedFileInTarget: AssetInfoFull;
    if (Array.isArray(assetInTarget)) {
      movedFileInTarget = assetInTarget.find(it => {
        const {relativePath} = it;
        return pathOnlyInTarget.includes(relativePath) && !pathOfMovedInTarget.includes(relativePath);
      });
    } else {
      const {relativePath} = assetInTarget;
      if (pathOnlyInTarget.includes(relativePath) && !pathOfMovedInTarget.includes(relativePath)) {
        movedFileInTarget = assetInTarget;
      }
    }
    /**
     * Find move action first, if not found, it's a copy action.
     * When do syncup using diff result, copy should be handled before move.
     */
    if (movedFileInTarget) {
      pathOfMovedInTarget.push(movedFileInTarget.relativePath);
      moved.push({
        from: movedFileInTarget,
        to: sourceAsset,
      });
    } else {
      copied.push({
        from: Array.isArray(assetInTarget) ? assetInTarget[0] : assetInTarget,
        to: sourceAsset,
      });
    }
  }
  for (const p of pathCommon) {
    const targetAsset = pathToAssetInTarget[p];
    const sourceAsset = pathToAssetInSource[p];
    const changed = diffAssets(sourceAsset, targetAsset, isSameDir ? ['modifyDate', 'size'] : ['sha1']);
    if (changed) {
      if (isSameDir) {
        /** Once there are asset props change, should recalculate assets sha1 */
        const sourceAssetFull = await toFullAssetInfo(sourceAsset, sourceRootDir);
        const changed2 = diffAssets(sourceAssetFull, targetAsset);
        if (changed2) {
          modified.push({
            from: targetAsset,
            to: sourceAssetFull,
            changed: changed,
          });
        }
      } else {
        modified.push({
          from: targetAsset,
          to: sourceAsset,
        });
      }
    }
  }

  deleted = pathOnlyInTarget.filter(p => !pathOfMovedInTarget.includes(p)).map(p => pathToAssetInTarget[p]);

  const isNeedAction =
    [added, copied, moved, modified, deleted].reduce<number>((sum, it) => {
      return sum + it.length;
    }, 0) > 0;

  return {
    toDir: targetRootDir,
    fromDir: sourceRootDir,
    isNeedAction,
    added,
    copied,
    moved,
    modified,
    deleted,
  };
}

export async function diffMetaForImportNew(
  toMeta: AssetMeta,
  fromMeta: AssetMeta
): Promise<MetaDiffForImportNew> {
  const {rootDir: rootDir1} = toMeta;
  const {rootDir: rootDir2} = fromMeta;
  const assetInfoList1 = getAssetInfoListFromMeta(toMeta);
  const assetInfoList2 = getAssetInfoListFromMeta(fromMeta);
  const sha1ToAssetInfo1 = getSha1ToAssetInfo(assetInfoList1);
  const sha1ToAssetInfo2 = getSha1ToAssetInfo(assetInfoList2);

  const newFiles: AssetInfoFull[] = [];
  const duplicatedFiles: MetaDiffForImportNew['duplicatedFiles'] = {};
  for (const key of Object.keys(sha1ToAssetInfo2)) {
    const assetInfo1 = sha1ToAssetInfo1[key];
    const assetInfo2 = sha1ToAssetInfo2[key];
    if (assetInfo1) {
      duplicatedFiles[key] = {
        origin: Array.isArray(assetInfo1) ? assetInfo1 : [assetInfo1],
        by: Array.isArray(assetInfo2) ? assetInfo2 : [assetInfo2],
      };
    } else {
      newFiles.push(await toFullAssetInfo(Array.isArray(assetInfo2) ? assetInfo2[0] : assetInfo2, rootDir2));
    }
  }
  const isNeedAction = newFiles.length > 0;
  return {isNeedAction, fromDir: rootDir2, toDir: rootDir1, newFiles, duplicatedFiles};
}

// export function diffAssetMeta(from: MetaInfo, to: MetaInfo) {}
export function serializeMetaDiff(stateChange: MetaDiffForSyncUp) {
  return {
    ...stateChange,
    added: stateChange.added?.map(it => serailizeAssetInfo(it)),
    deleted: stateChange.deleted?.map(it => serailizeAssetInfo(it)),
    copied: stateChange.copied?.map(it => {
      return {
        ...it,
        from: serailizeAssetInfo(it.from),
        to: serailizeAssetInfo(it.to),
      };
    }),
    moved: stateChange.moved?.map(it => {
      return {
        ...it,
        from: serailizeAssetInfo(it.from),
        to: serailizeAssetInfo(it.to),
      };
    }),
    modified: stateChange.modified?.map(it => {
      return {
        ...it,
        from: serailizeAssetInfo(it.from),
        to: serailizeAssetInfo(it.to),
        changed: serailizeAssetInfo(it.changed),
      };
    }),
  };
}
